### ISSUE TITLE
Raspberry Pi 4 GPU Acceleration only partially enabled?

### ISSUE THREAD

**Issue by sashahilton00** [balena-io-experimental/browser#121]
Hi,

I have been testing this block out in the hopes of using if for a kiosk where hardware accelerated graphics are required. After launching the block with the following configuration:

```yaml
browser:
    image: bhcr.io/balenablocks/browser-aarch64
    privileged: true
    network_mode: host
    ports:
      - '5011'
    volumes:
      - 'browser-settings:/data'

    environment:
      LAUNCH_URL: 'https://testufo.com/'
      KIOSK: 0
      SHOW_CURSOR: 1
      ENABLE_GPU: 1
```

The `chrome://gpu` page is reporting that only rasterization is hardware accelerated - canvas, compositing and video decode are all software only, and opengl/webgl are unavailable all together. Please find attached a pastebin link for the full log from `chrome://gpu`: [https://pastebin.com/XkZbdS75](https://pastebin.com/XkZbdS75)

Is there something basic that I am missing? @rahul-thakoor commented on the balena forums a while back about needing to use a Pi specific build of chromium, but looking through this repo it looks as though any pi specific stuff has been removed/replaced by the generic aarch64 image. Thread is [here](https://forums.balena.io/t/raspberry-pi-4-gpu-acceleration-for-chromium-browser/36959/22). When trying the older, unmaintained balena blocks image hosted on Docker ([balenablocks/browser:raspberrypi4-64](https://hub.docker.com/layers/browser/balenablocks/browser/raspberrypi4-64/images/sha256-902ff6cfb0f7d2ed888ecf0be0e85280d768d9ef29689ae6e54686d6414ff245?context=explore)) the hardware acceleration is fully functional. A pastebin of the `chrome://gpu` report when running that block is available here: [https://pastebin.com/1B5TsJtz](https://pastebin.com/1B5TsJtz), which shows hardware acceleration working as expected.

Any thoughts on where I might be going wrong would be much appreciated.
