### ISSUE TITLE
Audio issues on RPi4

### ISSUE THREAD

**Issue by ebradbury** [balena-io-experimental/browser#139]
In order for me to get headphone audio working on RPi4 I had to do the following:

- remove `vc4-kms-v3d` from the DT overlay variable in the dashboard
- put both `browser` and `audio` blocks in `network_mode: host`
- set `PULSE_SERVER: 'tcp:localhost:4317'` in `browser` environment
- set `AUDIO_OUTPUT: RPI_HEADPHONES` in `audio` environment

I wasn't able to get any audio (HDMI or headphones) with any other configuration. Hope this helps someone

**Comment by MiroYld** [comment]
Hi @ebradbury 

Here is an example deployment file that should help you
```
audio:
    restart: always
    image: 'balenablocks/audio:raspberrypi4-64'
    privileged: true
    labels:
      io.balena.features.dbus: '1'
    volumes:
      - 'src:/src'
    networks:
      - audio
      
  your_app:
    image: 'your_image'
    privileged: true
    environment:
      PULSE_SERVER: 'audio:4317'
    networks:
      - audio
      
networks:
  your_app:
    driver: bridge
  audio:
    driver: bridge
```
Please let me know if this solves your problem.
If you use waveshare speakers, you can also try my solution : https://github.com/MiroYld/smartaudio-docker
