### ISSUE TITLE
Poor WebGL performance on RPi5

### ISSUE THREAD

**Issue by deregtd** [balena-io-experimental/browser#172]
I'm using the browser module out of the box (v2.7.0) on my 8GB Raspberry Pi 5, with ENABLE_GPU=1 and other such niceties, on a 1080p touchscreen on HDMI, all deployed via balena:
```
  browser:
    image: bh.cr/balenalabs/browser-aarch64:v2.7.0
    network_mode: host
    privileged: true
    environment:
      LAUNCH_URL: "http://localhost"
      KIOSK: 0
      PERSISTENT: 1
      ENABLE_GPU: 1
      WINDOW_SIZE: 1920,1080
    labels:
      io.balena.features.dbus: "1"
    volumes:
      - browser-data:/data
```
My application is a webgl-based application that does map rendering, and poor performance (1fps even though the render function takes ~15ms to run) is pointing to something very wrong with the hardware pipeline on the balena block.  I then tried doing the basic [WebGL Aquarium sample](https://webglsamples.org/aquarium/aquarium.html) and the browser gets 7-8fps on there with 500 fish (default mode).  Even when I disable all the maps so my application is rendering a blank screen with an arrow in the center, it's still only getting 7-8fps (with a render function well below 1ms now).

I've checked chrome://gpu and all the usual stuff is enabled.  [Other benchmarks on a Pi5](https://www.youtube.com/watch?v=GJkzCxdPGHI) suggest that I should be getting 30-40fps.

Any idea what's up here?  It's looking like I'm going to have to bail on having a pi5 power my kiosk and just get a cheap android tablet to hit the website served by the pi remotely.
